# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100  

# Position Controllers ---------------------------------------
wheel_left_joint_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: wheel_left_joint
  pid: {p: 10.0, i: 0, d: 0.0}
wheel_right_joint_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: wheel_right_joint
  pid: {p: 10.0, i: 0, d: 0.0}
prism_joint_position_controller:
  type: effort_controllers/JointVelocityController # JointPositionController
  joint: prism_joint
  pid: {p: 5000.0, i: 0, d: 0.0}